### ISSUE TITLE
Add support for MDES disposition codes

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/ncs_mdes#3]
Have the specification load disposition codes from the Master Data Element Specification spreadsheet

**Comment by rsutphin** [comment]
Some of the codes in the YAML file are not delimited as strings. [Line 390](https://github.com/NUBIC/ncs_mdes/commit/83fdd07c7b6f8dd832dd68bdd9f3ed361ebe67f5#L1R390) is an example:

```
interim_code: 038
```

I thought that, since a leading zero means octal, this wasn't going to parse correctly, but the YAML appears to have very specifically been rendered such that only cases where it couldn't be an octal value (i.e., because it contains an 8 or a 9) are missing the quotation marks.

```
$ irb
ruby-1.8.7-p334 :001 > require 'yaml'
 => true 
ruby-1.8.7-p334 :002 > YAML.load('interim_code: 038')
 => {"interim_code"=>"038"} 
ruby-1.8.7-p334 :003 > YAML.load('interim_code: 037')
 => {"interim_code"=>31} 
```
